# Generated by Django 3.2.9 on 2023-06-13 17:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import todoListApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2023, 6, 13, 17, 3, 44, 956885, tzinfo=utc))),
                ('due_date', models.DateTimeField(default=todoListApp.models.one_week_hence)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todoListApp.category')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoListApp.state')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('todoList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoListApp.todolist')),
            ],
        ),
    ]
